### ISSUE TITLE
Project Updates

### ISSUE THREAD

**Issue by pidgeon777** [Ekopalypse/NppPythonScripts#9]
Hello, this seems to be an interesting project, I was wondering whether or not his development was continuing.

**Comment by Ekopalypse** [comment]
@pidgeon777 
What do you mean. The Python-based language server protocol implementation or the scripts in general?
When it comes to the lsp, no, it's not dead, but I found a new programming language called [V](https://vlang.io/) and I'm currently spending my free time learning it and contributing to its ecosystem. In the end, I hope to create an lsp plugin using V.

**Comment by pidgeon777** [comment]
Hello, I apologize if I was unclear.

What I meant, is that enabling LSP in Notepad++ would be very cool (no matter of the chosen programming language), and your project seemed to be oriented in doing exactly that.

Thus, I was wondering if the development of a plugin to enable LSP in Notepad++, was still ongoing on your side.

**Comment by Stem75** [comment]
Hello and thanks for your code.

I am not a programmer and i only registered here just to ask you about this part of your code:

(
Now, if a regular expression like "(?:(?:def)\s\w+)\s*\((.+)\):" were used to color all parameters,
then this would only work as long as the line "def my_function(param1," is visible.

A possible approach to avoid this would be to define an offset range.

offset_start_line = start_line - offset
if offset_start_line < 0 then offset_start_line = 0
)

I have a regex like this:

ahk_regexes[(1, (130, 150, 160))] = (r'/\*[^*]*\*+(?:[^/*][^*]*\*+)*/', 0)

And in notepad++ the part bellow it isn't highlighted because it is out of visible area.
( When i delete some lines it is working fine ).


/*
	class RichCode({"TabSize": 4     ; Width of a tab in characters
    
	, "Indent": "`t"             ; What text to insert on indent
    
	, "FGColor": 0xRRGGBB        ; Foreground (text) color
    
	, "BGColor": 0xRRGGBB        ; Background color
    
	, "Font"                     ; Font to use
    
	: {"Typeface": "Courier New" ; Name of the typeface
	, "Size": 12             ; Font size in points
	, "Bold": False}         ; Bolded (True/False)
	
	
	; Whether to use the highlighter, or leave it as plain text
	, "UseHighlighter": True
	
	; Delay after typing before the highlighter is run
	, "HighlightDelay": 200
	
	; The highlighter function (FuncObj or name)
	; to generate the highlighted RTF. It will be passed
	; two parameters, the first being this settings array
	; and the second being the code to be highlighted
	, "Highlighter": Func("HighlightAHK")
	
	; The colors to be used by the highlighter function.
	; This is currently used only by the highlighter, not at all by the
	; RichCode class. As such, the RGB ordering is by convention only.
    
    
	; You can add as many colors to this array as you want.
	, "Colors"
	: [0xRRGGBB
	, 0xRRGGBB
	, 0xRRGGBB,
	, 0xRRGGBB]})
*/


I've searched the internet for an answer but i haven't find anything.
Can you give me an example as of what to replace in your code to make it work for all the matched lines?

Thanks in advance.

**Comment by Ekopalypse** [comment]
Assuming an offset of 40 additional lines, add the 4 extra lines to the style method.
The price is that the more extra lines that have to be searched for and styled, the more likely it is that there will be noticeable delays.

~~~py
        start_line = editor.docLineFromVisible(editor.getFirstVisibleLine())
        end_line = editor.docLineFromVisible(start_line + editor.linesOnScreen())
        if editor.getWrapMode():
            end_line = sum([editor.wrapCount(x) for x in range(end_line)])
        
        # new
        offset = 40
        start_line = 0 if start_line < offset else start_line-offset
        
        total_lines = editor.getLineCount()
        end_line = total_lines if end_line+offset > total_lines else end_line+offset
        # new end
        
        onscreen_start_position = editor.positionFromLine(start_line)
        onscreen_end_pos = editor.getLineEndPosition(end_line)
~~~

Make sure that you use the same indentation symbols (spaces or tabs) when copying/pasting in your code. Python is picky about this.

**Comment by Stem75** [comment]
Thank you very much for your fast reply.
It is working fine ( I've added 140 ).
For me the minor delays are acceptable for a nice looking highlighted text.
Keep up the good work!!!

**Comment by Ekopalypse** [comment]
@Stem75 - I have created a dedicated plugin [here](https://github.com/Ekopalypse/EnhanceAnyLexer/releases), which should probably have better performance than the PS solution. One disadvantage is that it can only handle main matches and not submatches. If that's not relevant for you, you can give it a try.
